name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ‘1.17.2’
    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.68.3
        TARGET_REPO: aviral-ag/aviral-ag.github.io 
        TOKEN: ${{ secrets.TOKEN }}
        #CNAME: www.jameswright.xyz 
